w10d1_rails_review/dogs/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

	# resources :breeds
	# resources :dogs

	resources :breeds do
		resources :dogs
	end

end

w10d1_rails_review/dogs/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

w10d1_rails_review/dogs/app/models/breed.rb
class Breed < ApplicationRecord
	has_many :dogs # breed.dogs()
end

w10d1_rails_review/dogs/app/models/dog.rb
class Dog < ApplicationRecord
	belongs_to :breed # dog.breed()
end

w10d1_rails_review/dogs/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

w10d1_rails_review/dogs/app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
	def index
		@breeds = Breed.all
	end
end

w10d1_rails_review/dogs/app/controllers/dogs_controller.rb
class DogsController < ApplicationController
	def index
		# @dogs = Dog.all

		breed_id = params[:breed_id]
		@breed = Breed.find(breed_id)
		@dogs = @breed.dogs()

	end
end

w10d1_rails_review/dogs/app/helpers/application_helper.rb
module ApplicationHelper
end

w10d1_rails_review/dogs/app/helpers/breeds_helper.rb
module BreedsHelper
end

w10d1_rails_review/dogs/app/helpers/dogs_helper.rb
module DogsHelper
end

w10d1_rails_review/dogs/app/views/breeds/index.html.erb
<h1>All the Breeds</h1>

<a href="/dogs">Dogs</a><br/>
<%= link_to 'Dogs', '/dogs' %><br/>


<% @breeds.each do |breed| %>
<div>
<h4>Breed: <%= breed.breed %></h4>
<%= link_to 'Dogs', breed_dogs_path(breed.id) %><br/>
</div>
<% end %>

w10d1_rails_review/dogs/app/views/dogs/index.html.erb
<h3>Dogs</h3>

All the dogs with breed id = <%= @breed.id %> (<%= @breed.breed %>)

<% @dogs.each do |dog| %>
<div class="dog">
<h2>ID: <%= dog.id %></h2>
<h2>NAME: <%= dog.name %></h2>
<h2>SOUND: <%= dog.sound %></h2>
<h2>AGE: <%= dog.age %></h2>
<h2>SIZE: <%= dog.size %></h2>
<h2>BREED: <%= dog.breed.breed %></h2>
</div>
<% end %>

w10d1_rails_review/dogs/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dogs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>